/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.server;

import edu.duke.ece651.risc.shared.ServerPlayer;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.mockito.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.atLeastOnce;

class AppTest {
  App app;

  @BeforeEach
  public void init() {
    MockitoAnnotations.initMocks(this);
    app = new App(hs, mockOut);
  }

  @Mock
  private PrintStream mockOut;

  @Mock
  private ServerSocket ss;

  @Mock
  private HostSocket hs;

  @Mock
  private ServerPlayer player;

  @Test
  void test_start_new_game() throws IOException {
    Socket s = new Socket();
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    ServerPlayer sp = new ServerPlayer(new BufferedReader(new StringReader("2\n")),
            new PrintWriter(bytes, true),s);
    ObjectMapper mapper = new ObjectMapper();
    JsonNode rootNode = mapper.readTree("{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"2\"}");
    Game g = app.startNewGame(sp,rootNode);
    assertEquals(2,g.getPlayerNum());
  }

 
  @Test
  void test_print_available_gameList() throws IOException {
    Socket socket1 = new Socket();      
    ByteArrayOutputStream bytes1 = new ByteArrayOutputStream();   
    ServerPlayer p1 = app.createOrUpdatePlayer("Red",new BufferedReader(new StringReader("")),new PrintWriter(bytes1, true),socket1);
    Socket socket2 = new Socket();      
    ByteArrayOutputStream bytes2 = new ByteArrayOutputStream();   
    Socket socket3 = new Socket();      
    ByteArrayOutputStream bytes3 = new ByteArrayOutputStream();   
    ServerPlayer p2 = app.createOrUpdatePlayer("Blue",new BufferedReader(new StringReader("")),new PrintWriter(bytes2, true),socket2);   
    ObjectMapper mapper = new ObjectMapper();
    JsonNode rootNode = mapper.readTree("{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"3\"}");                                                                                             
    Game g1 = app.startNewGame(p1,rootNode);
    Game g2 = app.startNewGame(p2,rootNode);
    assertEquals("[{\"id\":1,\"players\":[\"Blue\"]}]\n[{\"id\":0,\"players\":[\"Red\"]}]", app.allGameList("Red"));
    app.createOrUpdatePlayer("Blue",new BufferedReader(new StringReader("")),new PrintWriter(bytes3, true),socket3);
    assertDoesNotThrow(()->{p2.sendMessage("msg");});
  }

  @Test
  void test_join_exist_game() throws IOException {
    Socket s = new Socket();
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    ServerPlayer sp = new ServerPlayer(new BufferedReader(new StringReader("")),
            new PrintWriter(bytes, true),s);
    Socket s1 = new Socket();
    ByteArrayOutputStream bytes1 = new ByteArrayOutputStream();
    ServerPlayer sp1 = new ServerPlayer(new BufferedReader(new StringReader("")),
            new PrintWriter(bytes1, true),s1);
    ObjectMapper mapper = new ObjectMapper();
    JsonNode rootNode = mapper.readTree("{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"2\"}");
    app.startNewGame(sp, rootNode);
    JsonNode rootNode1 = mapper.readTree("{\"type\":\"join\",\"name\":\"p2\",\"gameID\":\"0\"}");
    Game g1 = app.joinExistingGame(sp1, rootNode1);
    assertEquals(0,g1.getGameID());
    assertEquals(2,g1.getAllPlayers().size());
  }

  @Test
  public void test_rejoinGame() throws IOException{
    Socket s = new Socket();
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    ServerPlayer sp = new ServerPlayer(new BufferedReader(new StringReader("")),new PrintWriter(bytes, true),s);
    ObjectMapper mapper = new ObjectMapper();
    JsonNode rootNode = mapper.readTree("{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"2\"}");
    Game g = app.startNewGame(sp, rootNode);
    Game g1 = app.startNewGame(sp, rootNode);
    app.rejoinGame(sp, 0);
    assertEquals(0,sp.getCurrentGame());
  }
  @Test
  void test_accept_player() throws IOException, InterruptedException {
    Socket cs = Mockito.mock(Socket.class);
    Socket cs1 = Mockito.mock(Socket.class);
    Socket cs2 = Mockito.mock(Socket.class);
    Socket cs3 = Mockito.mock(Socket.class);
    String clientIn = "{\"type\":\"getGameList\",\"name\":\"test\"}\n";
    String clientIn1 = "{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"3\"}\n";
    String clientIn2 = "{\"type\":\"getGameList\",\"name\":\"p2\"}\n";
    String clientIn3 = "{\"type\":\"join\",\"name\":\"p2\",\"gameID\":\"0\"}\n";
    OutputStream out = getMockClientOuput(cs, clientIn);
    OutputStream out1 = getMockClientOuput(cs1, clientIn1);
    OutputStream out2 = getMockClientOuput(cs2, clientIn2);
    OutputStream out3 = getMockClientOuput(cs3, clientIn3);
    Mockito.when(ss.accept()).thenReturn(cs).thenReturn(cs1).thenReturn(cs2).thenReturn(cs3);
    Thread t = new Thread(() -> {
      try {
        app.acceptPlayers(ss);
      } catch (NullPointerException ignored) {
      }
    });
    t.start();
    // wait for "acceptPlayers" finishing
    Thread.sleep(2000);
    // check the player's out - it should have sth???
    assertEquals("[]\n[]\n[{\"id\":0,\"players\":[\"test\"]}]\n[]\nYou are in a Game now!\n", out.toString()+out1.toString()+out2.toString()+out3.toString());
    // end the acceptPlayers
    t.interrupt();
    t.join();
  }



  private OutputStream getMockClientOuput(Socket cs, String clientIn) throws IOException {
    InputStream in = new ByteArrayInputStream(clientIn.getBytes());
    OutputStream out = new ByteArrayOutputStream();
    Mockito.when(cs.getInputStream()).thenReturn(in);
    Mockito.when(cs.getOutputStream()).thenReturn(out);
    return out;
  }
/*
  @Test
  void test_accept_player_exception_handling() throws IOException, InterruptedException {
    Socket cs = Mockito.mock(Socket.class);
    String clientIn = "3\n";
    OutputStream out = getMockClientOuput(cs, clientIn);
    Mockito.when(ss.accept()).thenReturn(cs).thenThrow(new IOException("test"));
    Thread t = new Thread(() -> {
      app.acceptPlayers(ss);
    });
    t.start();
    // wait for "acceptPlayers" finishing
    Thread.sleep(1000);
    // should print IOEexception in server's app
    Mockito.verify(mockOut, atLeastOnce()).println(anyString());
    t.interrupt();
    t.join();
  }

  @Test
  void test_run() throws IOException, InterruptedException {
    // prep
    Socket cs = Mockito.mock(Socket.class);
    String clientIn = "3\n";
    Mockito.when(ss.accept()).thenReturn(cs).thenThrow(new IOException("test"));
    OutputStream out = getMockClientOuput(cs, clientIn);
    Mockito.when(hs.getSocket()).thenReturn(ss);
    // start
    app = new App(hs, mockOut);
    Thread t = new Thread(() -> {
      app.run();
    });
    t.start();
    Thread.sleep(2000);
    t.interrupt();
    t.join();
    Mockito.verify(hs).getSocket();
    Mockito.verify(hs).closeSocket();
  }*/

  @Test
  void test_allGameList() throws IOException{
    Socket s = new Socket();
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    ServerPlayer sp = new ServerPlayer(new BufferedReader(new StringReader("")),
            new PrintWriter(bytes, true),s);
    sp.setName("Red");
    ObjectMapper mapper = new ObjectMapper();
    JsonNode rootNode = mapper.readTree("{\"type\":\"start\",\"name\":\"test\",\"gameSize\":\"3\"}");
    app.startNewGame(sp,rootNode);
    String str = app.allGameList(sp.getName());
    assertEquals("[]\n[{\"id\":0,\"players\":[\"Red\"]}]",str);
  }
}
