/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.server;

import java.util.ArrayList;

import edu.duke.ece651.risc.shared.Player;

public class App {
    /**
     * all players socket for the game
     * ClientSokct includes socket, inputStream, outputStream
     */
     ArrayList<Player> players;


    /*public String getGreeting() {
        return "Hello world.";
    }*/

    /**
     * 
     * @param clients
     */
    public App(ArrayList<Player> players){
        this.players = players;
    }

    /**
     * The main function to run
     * @param args
     */
    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        /*if (args.length != 2) {
            System.err.println("need parameter <port number> <Player number>");
            System.exit(1);
        }*/
        int portNumber = 4444;
        int playerNum = 1;
        HostSocket hs = new HostSocket(portNumber,playerNum);
        App myapp = new App(hs.waitForConnections());
        System.out.println("There are "+myapp.players.size()+" players");
    }


}












